name: Cache stack

on:
  push:
    branches:
      - main
jobs:
  
  cache:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Set up node
        uses: actions/setup-node@v2
        with:
          node-version: 16.x
          cache-dependency-path: package-lock.json
          cache: 'npm'
      - run: npm install
      - name: Turbo Cache
        id: turbo-cache
        uses: actions/cache@v2
        with:
          path: .turbo
          key: turbo-${{ github.job }}-${{ github.ref_name }}-${{ github.sha }}
          restore-keys: |
            turbo-${{ github.job }}-${{ github.ref_name }}-
      - name: Build repo
        run: npm run build -- -vvv --cache-dir=".turbo"
