name: Cache stack

on:
  push:
    branches:
      - main
jobs:
  
  cache:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Set up node
        uses: actions/setup-node@v2
        with:
          node-version: 16.x
          cache: 'npm'
      - run: npm install
      - name: Restore turbo cache
        uses: actions/cache@v2
        with:
          path: node_modules/.cache
          key: ${{ runner.os }}-cache-${{ github.ref_name }}
          restore-keys: |
            ${{ runner.os }}-cache-v2-${{ github.ref_name }}
            ${{ runner.os }}-cache-v2-
      - name: Build repo
        run: npm run build
